# Generated by Django 2.0.2 on 2018-03-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_stickerpack_path_to_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='stickerpack',
            name='path_to_image',
        ),
    ]
